services:
  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dance-frontend
    ports:
      - "80:3000"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dance-backend
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=DanceStudio;Username=postgres;Password=sas07291mem
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: dance-db
    environment:
      POSTGRES_DB: dance_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: